- hosts: localhost
  become: yes
  tasks:
    - name: Certificar-se de que pacman está atualizado
      pacman:
        update_cache: yes

    - name: Instalar pacotes desejados
      pacman:
        name:
          - git
          - neovim
          - tmux
          - alacritty
          - fish
          - docker
          - kubectl
          - azure-cli
          - aws-cli
          - exa
          - curl
          - dog
          - bat
          - jq
          - yq
          - gping
          - vlc
        state: present
