- hosts: localhost
  become: yes
  tasks:
    - name: Update pacman cache
      pacman:
        update_cache: yes

    - name: Install desired packages
      pacman:
        name:
          - git
          - neovim
          - tmux
          - alacritty
          - fish
          - docker
          - kubectl
          - kubectx
          - azure-cli
          - aws-cli
          - exa
          - curl
          - dog
          - bat
          - jq
          - yq
          - gping
          - vlc
          - obsidian
          - ttf-cascadia-code
          - ttf-fira-code
          - flameshot
          - zenith
        state: present

    - name: Add user to docker group
      user:
        name: rockshimomime
        groups: docker
        append: yes
